### ISSUE TITLE
Missing helper file helpers/spree/store_helper.rb (LoadError) 

### ISSUE THREAD

**Issue by sfcgeorge** [spree/spree_auth_devise#55]
On updating the gemfile I'm getting the below error, though oddly only after I've pushed to Heroku. Running in development locally is fine. I think this might be the gem at fault as I kept all the versioned gems the same, so the problem must have been introduced in one of the GitHub sourced gems.

I wonder if this commit could be what introduced the issue? 5682a5685982bb65563709c8f411df62ba8523d5

Any thoughts welcome, thanks.

```
2013-02-12T00:01:12+00:00 app[web.1]: /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:317:in `rescue in depend_on': Missing helper file helpers/spree/store_helper.rb (LoadError)
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:312:in `depend_on'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:225:in `require_dependency'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/helpers.rb:135:in `block in modules_for_helpers'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/action_controller/metal/helpers.rb:92:in `modules_for_helpers'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/bundler/gems/spree_auth_devise-5682a5685982/app/controllers/spree/user_passwords_controller.rb:3:in `<class:UserPasswordsController>'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/helpers.rb:131:in `map!'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/bundler/gems/spree_auth_devise-5682a5685982/app/controllers/spree/user_passwords_controller.rb:1:in `<top (required)>'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:313:in `depend_on'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:359:in `require_or_load'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/helpers.rb:131:in `modules_for_helpers'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:225:in `require_dependency'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:438:in `block in eager_load!'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in `each'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:436:in `eager_load!'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `instance_exec'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:436:in `each'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:434:in `eager_load!'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in `all'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:55:in `block in run_initializers'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.12/lib/abstract_controller/helpers.rb:95:in `helper'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `run_initializers'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
2013-02-12T00:01:12+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'

```

**Comment by piousbox** [comment]
![ 2022-10-19 a la(s) 1214](https://user-images.githubusercontent.com/831744/196759698-d4e68763-7de8-4488-bc73-fa83ca525aad.jpg)

The problem, or a variation of the same, appears to still be there, 9 years later.
